require_relative 'app'
require 'active_record'


task :default => :migrate

desc "Run migrations"
namespace :db do
  task :migrate do
    ActiveRecord::Migrator.migrate('db/migrate', ENV["VERSION"] ? ENV["VERSION"].to_i : nil)
  end
end

desc "Load app and open pry"
task :console do
  require 'pry'
  exec "pry -r./app.rb"
  ARGV.clear
  Pry.start
end
