require_relative 'app'
desc "Run Migrations"
namespace :db do
  task :migrate do
    ActiveRecord::Migrator.migrate('db/migrate', ENV["VERSION"] ? ENV["VERSION"].to_i : nil)
  end
end

desc "load my app.rb and open pry"
task :console do
  require 'pry'
  exec "pry -r ./app.rb"
  Pry.start
end
